### ISSUE TITLE
Change the examples to not use the Chrome extension

### ISSUE THREAD

**Issue by minisu** [Yubico/php-u2flib-server#22] opened 2015-04-24 05:48 UTC
Since the Chrome extension is no longer required. See [here](https://github.com/Yubico/java-u2flib-server/blob/master/u2flib-server-demo/src/main/resources/demo/view/register.ftl) for an example.

**Comment by klali** [comment] 2015-04-24 07:46
duplicate of #18

**Closed by klali** 2015-04-24 07:46 UTC
